columns:
  step: int
  type: object
  amount: float
  nameOrig: object
  oldbalanceOrg: float
  newbalanceOrig: float
  nameDest: object
  oldbalanceDest: float
  newbalanceDest: float
  isFraud: int
  isFlaggedFraud: int

target_column: isFraud

numerical_columns:
  - step
  - amount
  - oldbalanceOrg
  - newbalanceOrig
  - oldbalanceDest
  - newbalanceDest
  - diff_in_balance_sender_account
  - receiver_balance_diff_account

categorical_columns:
  - type

drop_columns:
  - nameOrig
  - nameDest
  - isFlaggedFraud
